# Generated by Django 4.0.5 on 2022-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_players',
            field=models.IntegerField(default=0),
        ),
    ]
