# Generated by Django 4.0.5 on 2022-07-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_total_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='selling_price',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='teams.team'),
        ),
    ]
