# Generated by Django 4.0.5 on 2022-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_player_rating_alter_player_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='remaining_budget',
            field=models.FloatField(default=100),
        ),
    ]
