# Generated by Django 4.0.5 on 2022-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='remaining_budget',
            field=models.FloatField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_players',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
