version: '3'

services:
  # Django web service
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cricwars_auction
    command: gunicorn auction.wsgi:application -w 4 -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
